Financial-Times/n-image

- .gitignore
- .travis.yml
- Makefile
- README.md
- bower.json
- demos/data.json
- demos/main.html
- main.js
- main.scss
- templates/image.html
> Initial version of n-image

- .travis.yml
- bower.json
- main.js
now included in origami's polyfill
> Remove picturefill

- .gitignore
- Makefile
- README.md
- main.js
- package.json
- templates/image.js
cc @tom-parker @ironsidevsquincy 
An equivalent version of the existing handlebars n-image template to work with ReactJS
> Add: ReactJS template

- bower.json
> Remove: Version: 0.0.0 from bower.json to enable nbt bottle

- README.md
- helpers/add-width.js
- helpers/build-url.js
- helpers/index.js
- main.js
- package.json
- templates/image.js
> Add: Function to build urls according to whether img service is reqd

- bower.json
> Amend: bower.json main to point to image.js template

- templates/image.html
> Amend: Handlebars template min-widths to match o-grid widths

- README.md
- templates/image.js
Also update docs in a more [JSDoc style](http://usejsdoc.org/tags-param.html)
cc: @andygout
> Add ability to pass in image service params

- templates/image.js
> Add: Quotes to srcset

- templates/image.js
If you don't want to do all that responsive image malarkey
Also, add a `lazyLoad` prop, which, for now, buts the `<img />` in a `noscript`
> Allow passing in of src property

- components/image.js
- main.scss
- src/lib/lazy-load.js
Needed for `IntersectionObserver` to work
Also tidy up class names
> Only give with if lazy loading

- src/lib/lazy-load.js
Plus, an optional root to search from
> Only lazy load once

- src/lib/lazy-load.js
Rather than a new one for each image
> Use a single IntersectionObserver

- components/image.js
- main.scss
- src/lib/lazy-load.js
- tests/templates/image.test.js
> Add placeholder

- bower.json
- src/lib/lazy-load.js
Just use standard load event listener for loading images
> Don't use imagesloaded lib

- bower.json
> add babelrc to bower's ignore

- README.md
- main.scss
- src/helpers/build-image-service-url.js
- tests/presenters/image.test.js
- tests/templates/image.test.js
> Switch from geebee to image service v2

- src/helpers/build-image-service-url.js
- tests/helpers/build-image-service-urls.test.js
> dont capture the -us

- src/presenters/image.js
> Switched back to console due to build errors

- Makefile
- bower.json
- demos/app.js
- demos/demo.html
- demos/fixtures.json
- demos/src/demo.scss
- package.json
Run `make demo` -> see n-image demo on port 5005. Pa11y tests coming in a separate PR.
@lc512k @GlynnPhillips
> Add demo server

- .pa11yci.js
- Makefile
- bower.json
- demos/app.js
- package.json
> Add pa11y to the test flow

- main.scss
> Fix for Edge intersectionObserver not working

- README.md
- bower.json
- demos/fixtures.json
- src/presenters/image.js
No [breaking changes](https://github.com/Financial-Times/n-ui-foundations/issues/34#issuecomment-341787777) for this module
> Bump n-ui-foundations to v3 beta

- .gitignore
- main.scss
> Linting fixes

- .pa11yci.js
- circle.yml
- package.json
> Upgrade to pa11y 2

- package.json
🐿 v2.8.0
This is to test out if our n-gage changes have any impact on lambdas (they shouldn't)
> Update n-gage and remove nht
